### ISSUE TITLE
x96+ Gigabit Port Lan

### ISSUE THREAD

**Issue by radityabh** [ophub/amlogic-s9xxx-openwrt#107]
why in kernel 5.4 gigabit port in x96+ not work? in kernel 5.13, i just change the uenv.txt and the gigabit port work normally. but in kernel 5.4 not work. Thanks You

**Comment by ophub** [comment]
- 5.4, 5.10 and 5.13 can be used.
- When used in USB, only 100M Ethernet is supported, and Gigabit is supported after writing into EMMC.
- There is no need to manually modify uEnv.txt. Whether it is used in USB or written to EMMC, there is an installation script to complete it automatically.
- If you find that 5.4 or a certain firmware cannot be used, please download it again, rewrite it to the USB and try again. Occasionally, it may not be able to boot from the USB due to incomplete writing of the disk.
